pipelines:
  branches:
    master:
      - step:
          name: Build
          services:
            - docker
          script:
            - apt-get -qq update && apt-get install -qq jq
            - export TERRAFORM_VERSION="$(./terraform-version.sh)"
            - export FULL_VERSION="${TERRAFORM_VERSION}-${BITBUCKET_BUILD_NUMBER}"
            - docker build --build-arg TERRAFORM_VERSION=${TERRAFORM_VERSION} -t truemark/terraform-aws:${FULL_VERSION} .
            - docker tag truemark/terraform-aws:${FULL_VERSION} truemark/terraform-aws:${TERRAFORM_VERSION}
            - docker tag truemark/terraform-aws:${FULL_VERSION} truemark/terraform-aws:latest
            - docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASS
            - docker push truemark/terraform-aws
