pipelines:
  branches:
    master:
      - step:
          name: Build
          image: alpine:latest
          services:
            - docker
          script:
            - apk add --no-cache bash curl jq
            - export TERRAFORM_VERSION="$(./terraform-version.sh)"
            - export FULL_VERSION="${TERRAFORM_VERSION}-${BITBUCKET_BUILD_NUMBER}"
            - docker build --build-arg TERRAFORM_VERSION=${TERRAFORM_VERSION} -t truemark/terraform-aws:${FULL_VERSION} .
            - docker tag truemark/terraform-aws:${FULL_VERSION} truemark/terraform-aws:${TERRAFORM_VERSION}
            - docker tag truemark/terraform-aws:${FULL_VERSION} truemark/terraform-aws:latest
            - docker build --build-arg SOURCE_IMAGE="truemark/terraform-aws:${FULL_VERSION}" -t truemark/terraform-aws-pipe:${FULL_VERSION} -f pipe.Dockerfile
            - docker tag truemark/terraform-aws-pipe:${FULL_VERSION} truemark/terraform-aws-pipe:${TERRAFORM_VERSION}
            - docker tag truemark/terraform-aws-pipe:${FULL_VERSION} truemark/terraform-aws-pipe:latest
            - docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASS
            - docker push truemark/terraform-aws
            - docker push truemark/terraform-aws-pipe
