name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Run at 6PM UTC every Monday
    - cron: '0 18 * * 1'

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
#      - name: Keepalive
#        uses: gautamkrishnar/keepalive-workflow@v1
      - name: Get Version
        run: |
          source ./version.sh
          echo "TERRAFORM_VERSION=${TERRAFORM_VERSION}" >> $GITHUB_ENV
          echo "TERRAFORM_MINOR_VERSION=${TERRAFORM_MINOR_VERSION}" >> $GITHUB_ENV
          echo "Terraform Version: ${TERRAFORM_VERSION}"
          echo "Terraform Minor Version: ${TERRAFORM_MINOR_VERSION}"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "${{ secrets.AWS_ASSUME_ROLE }}"
          aws-region: "us-east-1"
          role-duration-seconds: 7200
      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Setup Buildx Remote Docker
        id: buildx
        uses: truemark/aws-buildx-remote-docker-instance-action@v4
        with:
          security-group-id: "${{ vars.SECURITY_GROUP_ID }}"
          subnet-id: "${{ vars.SUBNET_ID }}"
          instance-profile: "${{ vars.INSTANCE_PROFILE }}"
          region: "us-east-2"


      - name: Build Base Image 5
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }} \
            --build-arg AWS_PROVIDER_VERSION=5 \
            -f Dockerfile \
            -t truemark/terraform-aws:${{ env.TERRAFORM_VERSION }}-5-${{ github.run_number }} \
            -t truemark/terraform-aws:${{ env.TERRAFORM_MINOR_VERSION }}-5 \
            .
      - name: Copy Base ${{ env.TERRAFORM_VERSION }}-5-${{ github.run_number }} to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/terraform-aws:${{ env.TERRAFORM_VERSION }}-5-${{ github.run_number }}"
          dest-image: "docker://public.ecr.aws/truemark/terraform-aws:${{ env.TERRAFORM_VERSION }}-5-${{ github.run_number }}"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy Base ${{ env.TERRAFORM_MINOR_VERSION }}-5 to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/terraform-aws:${{ env.TERRAFORM_MINOR_VERSION }}-5"
          dest-image: "docker://public.ecr.aws/truemark/terraform-aws:${{ env.TERRAFORM_MINOR_VERSION }}-5"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"


      - name: Build Pipe Image 5
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg SOURCE_IMAGE="truemark/terraform-aws:${{ env.TERRAFORM_VERSION}}-5-${{ github.run_number }}" \
            -f pipe.Dockerfile \
            -t truemark/terraform-aws-pipe:${{ env.TERRAFORM_VERSION }}-5-${{ github.run_number }} \
            -t truemark/terraform-aws-pipe:${{ env.TERRAFORM_MINOR_VERSION }}-5 \
            .
      - name: Copy Pipe ${{ env.TERRAFORM_VERSION }}-5-${{ github.run_number }} to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/terraform-aws-pipe:${{ env.TERRAFORM_VERSION }}-5-${{ github.run_number }}"
          dest-image: "docker://public.ecr.aws/truemark/terraform-aws-pipe:${{ env.TERRAFORM_VERSION }}-5-${{ github.run_number }}"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy Pipe ${{ env.TERRAFORM_MINOR_VERSION }}-5 to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/terraform-aws-pipe:${{ env.TERRAFORM_MINOR_VERSION }}-5"
          dest-image: "docker://public.ecr.aws/truemark/terraform-aws-pipe:${{ env.TERRAFORM_MINOR_VERSION }}-5"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"


      - name: Build Base Image 4
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }} \
            --build-arg AWS_PROVIDER_VERSION=4 \
            -f Dockerfile \
            -t truemark/terraform-aws:${{ env.TERRAFORM_VERSION }}-4-${{ github.run_number }} \
            -t truemark/terraform-aws:${{ env.TERRAFORM_MINOR_VERSION }}-4 \
            -t truemark/terraform-aws:latest \
            .
      - name: Copy Base ${{ env.TERRAFORM_VERSION }}-4-${{ github.run_number }} to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/terraform-aws:${{ env.TERRAFORM_VERSION }}-4-${{ github.run_number }}"
          dest-image: "docker://public.ecr.aws/truemark/terraform-aws:${{ env.TERRAFORM_VERSION }}-4-${{ github.run_number }}"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy Base ${{ env.TERRAFORM_MINOR_VERSION }}-4 to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/terraform-aws:${{ env.TERRAFORM_MINOR_VERSION }}-4"
          dest-image: "docker://public.ecr.aws/truemark/terraform-aws:${{ env.TERRAFORM_MINOR_VERSION }}-4"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy Base latest to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/terraform-aws:latest"
          dest-image: "docker://public.ecr.aws/truemark/terraform-aws:latest"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"


      - name: Build Pipe Image 4
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg SOURCE_IMAGE="truemark/terraform-aws:${{ env.TERRAFORM_VERSION}}-4-${{ github.run_number }}" \
            -f pipe.Dockerfile \
            -t truemark/terraform-aws-pipe:${{ env.TERRAFORM_VERSION }}-4-${{ github.run_number }} \
            -t truemark/terraform-aws-pipe:${{ env.TERRAFORM_MINOR_VERSION }}-4 \
            -t truemark/terraform-aws-pipe:latest \
            .
      - name: Copy Pipe ${{ env.TERRAFORM_VERSION }}-4-${{ github.run_number }} to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/terraform-aws-pipe:${{ env.TERRAFORM_VERSION }}-4-${{ github.run_number }}"
          dest-image: "docker://public.ecr.aws/truemark/terraform-aws-pipe:${{ env.TERRAFORM_VERSION }}-4-${{ github.run_number }}"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy Pipe ${{ env.TERRAFORM_MINOR_VERSION }}-4 to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/terraform-aws-pipe:${{ env.TERRAFORM_MINOR_VERSION }}-4"
          dest-image: "docker://public.ecr.aws/truemark/terraform-aws-pipe:${{ env.TERRAFORM_MINOR_VERSION }}-4"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy Pipe latest to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/terraform-aws-pipe:latest"
          dest-image: "docker://public.ecr.aws/truemark/terraform-aws-pipe:latest"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
